{
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-prettier",
    "stylelint-prettier/recommended"
  ],
  "plugins": [
    "stylelint-scss",
    "stylelint-order",
    "stylelint-prettier"
  ],
  "rules": {
    "at-rule-no-unknown": null,
    "selector-no-qualifying-type": true, # セレクタとクラスを結合させるのは禁止
    "property-no-vendor-prefix": true, # ベンダープレフィックスは不要
    "at-rule-no-vendor-prefix": true,
    "selector-no-vendor-prefix": true,
    "media-feature-name-no-vendor-prefix": true,
    "font-weight-notation": "named-where-possible", # font-weightは数値入力禁止
    "selector-pseudo-element-colon-notation": "double", ##擬似要素のセミコロンは2つ
    "scss/at-rule-no-unknown": true,
    "order/properties-alphabetical-order": true,
    "prettier/prettier": true,
  }
}
